### ISSUE TITLE
CUDA out of memory when runnig the code from example

### ISSUE THREAD

**Issue by aleh4d** [utterworks/fast-bert#286]
I tried to run the code from example on the fast-bert page, but got out of GPU memory error:

Exception has occurred: RuntimeError
CUDA out of memory. Tried to allocate 192.00 MiB (GPU 0; 6.00 GiB total capacity; 4.35 GiB already allocated; 84.91 MiB free; 4.44 GiB reserved in total by PyTorch)

**Comment by TingNLP** [comment]
modify **max_seq_length** and **max_seq_length** 
you can refer

**Comment by JayDew** [comment]
Could you please share what values worked for you? I also cannot run the examples

**Comment by Elzic6** [comment]
only way (works for me each time I have the same issue) is to make a "factory reset runtime" 
![image](https://user-images.githubusercontent.com/79973378/117663895-707ca500-b1a1-11eb-9408-435d6bcb421b.png)
